#!/bin/sh
set -e
exec >/dev/null 2>/dev/null
./git-fs umount || true
trap 'kill $pid' EXIT
./git-fs help
./git-fs fuse-help
! ./git-fs NO-SUCH-COMMAND
! ./git-fs is-mounted
./git-fs mount & pid=$!
./git-fs is-mounted
! ps -fp "$pid"
! ./git-fs
cat "$(./git-fs show-mountpoint)"/HEAD/worktree/README
cat "$(./git-fs show-mountpoint)"/heads/master/current/msg
cat "$(./git-fs show-mountpoint)"/heads/master/current/diff
! readlink "$(./git-fs show-mountpoint)"/heads/master
! cat "$(./git-fs show-mountpoint)"/heads/master
! ls "$(./git-fs show-mountpoint)"/HEAD/worktree/README/
find "$(./git-fs show-mountpoint)"
# Tree crashes (!); sometimes -C, or a pty, slows it down and helps.
#tree -Cal "$(./git-fs show-mountpoint)" || true
tree -al "$(./git-fs show-mountpoint)" || true
./git-fs umount
./git-fs umount || true

